/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  demoSidebars: [
    {
      type: 'autogenerated',
      dirName: '.' // This must remain `.` if your new docs instance is in the base directory
    }
  ],
};

module.exports = sidebars;
