// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  demoSidebars: [
    {
      type: 'autogenerated',
      dirName: '.' // This must remain `.` if your new docs instance is in the base directory
    }
  ],


};

module.exports = sidebars;
